In [1]:
import pandas as pd

df = pd.read_csv("/Users/santoshchunduru/Downloads/2026-02/2026-02-south-wales-street.csv")

df.head()
print(df.shape)
print(df.columns)
df.info()

(9002, 12)
Index(['Crime ID', 'Month', 'Reported by', 'Falls within', 'Longitude',
       'Latitude', 'Location', 'LSOA code', 'LSOA name', 'Crime type',
       'Last outcome category', 'Context'],
      dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 9002 entries, 0 to 9001
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Crime ID               8063 non-null   str
 1   Month                  9002 non-null   str
 2   Reported by            9002 non-null   str
 3   Falls within           9002 non-null   str
 4   Longitude              8831 non-null   float64
 5   Latitude               8831 non-null   float64
 6   Location               9002 non-null   str
 7   LSOA code              8831 non-null   str
 8   LSOA name              8831 non-null   str
 9   Crime type             9002 non-null   str
 10  Last outcome category  8063 non-null   str
 11  Context                0 non-null      float64
dtypes: float64(3), str(9)
memory usage: 844.1 KB

In [2]:
import pandas as pd
import glob
import os

folder_path = "/Users/santoshchunduru/Downloads/crime_data/*.csv"

file_list = glob.glob(folder_path)

all_dfs = []

for file in file_list:
    df= pd.read_csv(file)
    filename = os.path.basename(file)
    month = filename[:7]
    df["Month"] = month
    all_dfs.append(df)
combined_df = pd.concat(all_dfs,ignore_index = True)
print(combined_df.shape)
combined_df = combined_df.sort_values(by = "Month", ascending = True)

(61139, 12)

In [3]:
combined_df.isnull().sum()
combined_df = combined_df.drop(columns = ["Context"])
combined_df.duplicated().sum()
combined_df.columns
combined_df.info
combined_df[combined_df.duplicated()].head(10)
combined_df = combined_df.drop_duplicates()
combined_df.shape
combined_df.dtypes
combined_df.nunique()
combined_df.head()
combined_df.tail()
combined_df = combined_df[combined_df["Location"] != "No Location"]
combined_df = combined_df.drop(columns = ["Reported by", "Falls within"])
combined_df.shape

(57790, 9)

In [50]:
class CrimeAnalyzer:

    def __init__(self,df):
        self.df = df
        
    def top_crime_counts(self,group_col,loc_id):
        grouped = self.count_distribution(group_col)
        top_10 = grouped.iloc[:loc_id]
        total_col = self.df.shape[0]
        top_10_per = (top_10["Count"]/total_col * 100).round(2)
        final_df = pd.concat([top_10 , top_10_per], axis = 1)
        final_df.columns = ["Crime Count", "Crime Percentage"]
        return final_df
        
    def total_crimes(self):
        return self.df.shape[0]
        
    def crimes_by_type(self,top_n):
        return self.top_crime_counts(group_col = "Crime type",loc_id = top_n)
        
    def crimes_by_outcome(self,top_n):
        return self.top_crime_counts(group_col = "Last outcome category", loc_id = top_n)

    def crimes_by_lsoa(self,top_n):
        return self. top_crime_counts(group_col = "LSOA name", loc_id = top_n)
    
    def crimes_by_loc(self,top_n):
        return self.top_crime_counts(group_col = "Location", loc_id = top_n)
        
    def count_distribution(self, group_col):
        grouped = self.df.groupby(group_col).size()
        sorted_columns = grouped.sort_values(ascending = False)
        finaldf = sorted_columns.to_frame(name = "Count")
        return finaldf
            
    def percentage_distribution(self,group_col):
        grouped = self.count_distribution(group_col)
        total_col = self.df.shape[0]
        percentage = (grouped["Count"]/ total_col* 100).round(2)
        finaldf = percentage.to_frame(name = "Percentage")
        

analyzer = CrimeAnalyzer(combined_df)
# result = analyzer.top_crime_counts("LSOA name", 10)
# print(result)
# print(analyzer.total_crimes())
# analyzer.crimes_by_type(10)
# analyzer.crimes_by_lsoa(10)
analyzer.crimes_by_loc(10)
# analyzer.crimes_by_outcome(10)
# analyzer.percentage_distribution("Crime type")
# analyzer.count_distribution("Crime type")

                                   Crime Count  Crime Percentage
Location
On or near Parking Area                   2661              4.60
On or near Supermarket                    1737              3.01
On or near Shopping Area                   980              1.70
On or near Petrol Station                  893              1.55
On or near Sports/Recreation Area          801              1.39
On or near Nightclub                       624              1.08
On or near Police Station                  345              0.60
On or near Hospital                        286              0.49
On or near Heol Eglwys Fair                223              0.39
On or near High Street                     211              0.37

In [47]:
class CrimeFilter:
    def __init__(self,df):
        self.df = df
    def filter_by_month(self,month):
        filtered_df = self.df[self.df["Month"] == month]
        return filtered_df 
    def filter_by_outcome(self,outcome):
        filtered_df = self.df[self.df["Last outcome category"] == outcome]
        return filtered_df
    def filter_by_crime(self, crime_type):
        filtered_df = self.df[self.df["Crime type"] == crime_type]
        return filtered_df
    def filter_by_location(self,location):
        filtered_df = self.df[self.df["Location"] == location]
        return filtered_df
    def filter_by_lsoa(self,lsoa):
        filtered_df = self.df[self.df["LSOA name"] == lsoa]
        return filtered_df

crime_filter = CrimeFilter(combined_df)
crime_filter.filter_by_month("2025-10").head()
crime_filter.filter_by_outcome("Unable to prosecute suspect").head()
crime_filter.filter_by_crime("Robbery").head()
crime_filter.filter_by_location("On or near Supermarket").head()
crime_filter.filter_by_lsoa("Vale of Glamorgan 003B").head()

,Crime ID,Month,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category
60084,cad9da76cf6b7effddaa80e3d3c42f91988231b523393e...,2025-08,-3.333307,51.388714,On or near Pentir Y De,W01001119,Vale of Glamorgan 003B,Violence and sexual offences,Status update unavailable
60083,7a24eef0c818d3b146812865670ddc4c83dd4dc77a386f...,2025-08,-3.306980,51.407481,On or near Parking Area,W01001119,Vale of Glamorgan 003B,Violence and sexual offences,Status update unavailable
60082,c77b5cc5afd4c7c7cf3eac8d63632b5bc093ffc1552336...,2025-08,-3.306980,51.407481,On or near Parking Area,W01001119,Vale of Glamorgan 003B,Violence and sexual offences,Unable to prosecute suspect
60081,f13b7f2860b973a086dd6868701ffb9ceea5a5cb0ef051...,2025-08,-3.325890,51.402593,On or near Parking Area,W01001119,Vale of Glamorgan 003B,Violence and sexual offences,Unable to prosecute suspect
60080,bc15a252c5eb723489d5b0ba0dcffca9f08927cca3dae0...,2025-08,-3.306980,51.407481,On or near Parking Area,W01001119,Vale of Glamorgan 003B,Violence and sexual offences,Status update unavailable

In [26]:
# Loop
months = combined_df["Month"].unique().tolist()
eda_results = {}
monthly_totals = {}
for month in months:
    monthly_df = crime_filter.filter_by_month(month)
    total = monthly_df.shape[0]
    monthly_totals[month] = total
eda_results["monthly_totals"]= monthly_totals

monthly_crime_types = {}
for month in months:
    monthly_df = crime_filter.filter_by_month(month)
    temp_analyser = CrimeAnalyzer (monthly_df)
    crime_distribution = temp_analyser.count_distribution("Crime type")
    monthly_crime_types[month] = month
eda_results["monthly_crime_types"] = monthly_crime_types

monthly_outcomes = {}
for month in months:
    monthly_df = crime_filter.filter_by_month(month)
    temp_analyser = CrimeAnalyzer(monthly_df)
    crime_distribution = temp_analyser.crimes_by_outcome(5)
    monthly_outcomes[month] = crime_distribution
eda_results["monthly_outcomes"] = monthly_outcomes
len(monthly_outcomes)


# Dictionary 
monthly_summary = {}

for month in months:
    monthly_summary[month] = {"total_crimes": monthly_totals[month], 
                              "crime_types" : monthly_crime_types[month], 
                              "outcomes" : monthly_outcomes[month]}

eda_results["monthly_summary"] = monthly_summary

In [38]:
def calculate_monthly_totals(df):
    months = df["Month"].unique().tolist()
    crimefilter = CrimeFilter(df)
    monthly_totals = {}
    for month in months:
        monthly_df = crime_filter.filter_by_month(month)
        total = monthly_df.shape[0]
        monthly_totals[month] = total
    return monthly_totals
monthly_totals = calculate_monthly_totals(combined_df)
monthly_totals

def calculate_monthly_crime_types(df):
    months = df["Month"].unique().tolist()
    crime_filter = CrimeFilter(df)
    monthly_crime_types = {}
    for month in months:
        monthly_df = crime_filter.filter_by_month(month)
        temp_analyser = CrimeAnalyzer(monthly_df)
        crime_distribution = temp_analyser.count_distribution("Crime type")
        monthly_crime_types[month] = crime_distribution
    return monthly_crime_types
monthly_crime_types = calculate_monthly_crime_types(combined_df)
monthly_crime_types

def calculate_monthly_outcomes(df):
    monthly_outcomes= {}
    months = df["Month"].unique().tolist()
    crime_filter = CrimeFilter(df)
    for month in months:
        monthly_df = crime_filter.filter_by_month(month)
        temp_analyser = CrimeAnalyzer(monthly_df)
        crime_outcome = temp_analyser.count_distribution("Last outcome category")
        monthly_outcomes[month] = crime_outcome 
    return monthly_outcomes
monthly_outcomes = calculate_monthly_outcomes(combined_df)
monthly_outcomes

{'2025-08':                                                     Count
 Last outcome category
 Unable to prosecute suspect                          3927
 Investigation complete; no suspect identified        2869
 Awaiting court outcome                               1137
 Status update unavailable                             775
 Further investigation is not in the public inte...    143
 Local resolution                                      143
 Offender given a caution                               34
 Formal action is not in the public interest            33
 Action to be taken by another organisation             16
 Suspect charged as part of another case                12,
 '2025-09':                                                     Count
 Last outcome category
 Unable to prosecute suspect                          3358
 Investigation complete; no suspect identified        2629
 Status update unavailable                             960
 Awaiting court outcome                                934
 Further investigation is not in the public inte...    161
 Local resolution                                      143
 Formal action is not in the public interest            36
 Offender given a caution                               23
 Action to be taken by another organisation             15
 Suspect charged as part of another case                 3,
 '2025-10':                                                     Count
 Last outcome category
 Unable to prosecute suspect                          3899
 Investigation complete; no suspect identified        2935
 Under investigation                                  1280
 Awaiting court outcome                                974
 Further investigation is not in the public inte...    169
 Local resolution                                      135
 Formal action is not in the public interest            35
 Action to be taken by another organisation             34
 Offender given a caution                               33
 Suspect charged as part of another case                 6,
 '2025-11':                                                     Count
 Last outcome category
 Unable to prosecute suspect                          3439
 Investigation complete; no suspect identified        2858
 Under investigation                                  1351
 Awaiting court outcome                                890
 Further investigation is not in the public inte...    178
 Local resolution                                      154
 Formal action is not in the public interest            27
 Offender given a caution                               23
 Action to be taken by another organisation             21
 Suspect charged as part of another case                 2,
 '2025-12':                                                     Count
 Last outcome category
 Unable to prosecute suspect                          2994
 Investigation complete; no suspect identified        2516
 Under investigation                                  1634
 Awaiting court outcome                                779
 Local resolution                                      143
 Further investigation is not in the public inte...    141
 Formal action is not in the public interest            27
 Offender given a caution                               26
 Action to be taken by another organisation             11
 Suspect charged as part of another case                 1,
 '2026-01':                                                     Count
 Last outcome category
 Under investigation                                  2604
 Unable to prosecute suspect                          2568
 Investigation complete; no suspect identified        2166
 Awaiting court outcome                                769
 Local resolution                                      115
 Further investigation is not in the public inte...    111
 Formal action is not in the public interest            23
 Offender given a caution                               10
 Action to be taken by another organisation              8
 Suspect charged as part of another case                 3}

In [60]:
def get_crimes_by_type(df,top_n):
    analyser = CrimeAnalyzer(df)
    top_crimes = analyser.crimes_by_type(top_n)
    return top_crimes
top_crimes = get_crimes_by_type(combined_df,10)
top_crimes

def get_crimes_by_outcome(df,top_n):
    analyser = CrimeAnalyzer(df)
    top_crimes_outcome = analyser.crimes_by_outcome(top_n)
    return top_crimes_outcome
top_crimes_outcome = get_crimes_by_outcome(combined_df,10)
top_crimes_outcome

def get_crimes_by_lsoa(df,top_n):
    analyzer = CrimeAnalyzer(df)
    crimes_by_loc = analyzer.crimes_by_lsoa(top_n)
    return crimes_by_loc
crimes_by_loc = get_crimes_by_lsoa(combined_df,10)
crimes_by_loc

def get_crimes_by_location(df,top_n):
    analyser = CrimeAnalyzer(df)
    crimes_by_loc = analyser.crimes_by_loc(top_n)
    return crimes_by_loc
crimes_by_loc = get_crimes_by_location(combined_df, 10)
crimes_by_loc

def get_unique_counts(df):
    unique_counts = {}
    unique_counts["Unique Crime type"] = df["Crime type"].nunique()
    unique_counts["Unique Location"] = df["Location"].nunique()
    unique_counts["Unique Last Outcome"] = df["Last outcome category"].nunique()
    unique_counts["Unique LSOA name"] = df["LSOA name"].nunique()
    return unique_counts

unique_summary = get_unique_counts(combined_df)
print(unique_summary)

{'Unique Crime type': 14, 'Unique Location': 8645, 'Unique Last Outcome': 11, 'Unique LSOA name': 922}